#------------------------------------------------------------------------------
# Portions of this file are Copyright (C)2019 Robert Cowart
# 
# Portions of this file are subject to the Robert Cowart Public License (the
# "License") and may not be used or distributed except in compliance with the
# License. You may obtain a copy of the License at:
# 
# http://www.koiossian.com/public/robert_cowart_public_license.txt
# 
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
# the specific language governing rights and limitations under the License.
# 
# The Original Source Code was developed by Robert Cowart. Portions created by
# Robert Cowart are Copyright (C)2019 Robert Cowart. All Rights Reserved.
#------------------------------------------------------------------------------

version: '3.1'

services:

  logstash:
    image: robcowart/elastiflow-logstash-oss:3.5.3
    restart: always
    environment:
      # JVM Heap size - this MUST be at least 3GB (4GB preferred)
      LS_JAVA_OPTS: '-Xms2g -Xmx3g'
      # ElastiFlow global configuration
      ELASTIFLOW_DEFAULT_APPID_SRCTYPE: "__UNKNOWN"
      ELASTIFLOW_ES_HOST: "192.168.186.100:9200"
      # Name resolution option
      ELASTIFLOW_RESOLVE_IP2HOST: "false"
      ELASTIFLOW_NAMESERVER: "127.0.0.1"
      ELASTIFLOW_NETFLOW_IPV4_PORT: 2055
      ELASTIFLOW_SFLOW_IPV4_PORT: 6343
      ELASTIFLOW_IPFIX_TCP_IPV4_PORT: 4739
    ports:
      - 2055:2055/udp        # Logstash Netflow  [ElastiFlow]
      - 6343:6343/udp        # Logstash sFlow    [ElastiFlow]
      - 4739:4739/tcp        # Logstash IPFIX    [ElastiFlow]
      - 4739:4739/udp        # Logstash IPFIX    [ElastiFlow]
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

