version: '3.1'

networks:
  external:
    external:
      name: proxy

services:
  syslog:
    image: rsyslog/syslog_appliance_alpine:latest
    hostname: rsyslog
    volumes:
      - /mnt/logs/data:/logs
    restart: always
    networks:
      - external
    ports:
      - 514:514/udp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
